spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:challenge03_microservices
    username: sa
    password: password
  #    url: jdbc:postgresql://localhost:5432/challenge03_microservices
  #    username: postgres
  #    password: password
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: ms-authorization

server:
  port: 9000
#  servlet:
#    context-path: /api
#logging:
#  level:
#    org:
#      springframework:
#        security: trace

