spring:
  security:
    oauth2:
      client:
        registration:
          client-server-oidc:
            provider: spring
            client-id: client-server
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid, profile
            client-name: client-server-oidc
        provider:
          spring:
            issuer-uri: http://localhost:9000
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          #          - id: authorization-server
          #            uri: http://localhost:9000
          #            predicates:
          #              - Path=/users/{id}
          - id: ms-products
            uri: http://localhost:9090
            predicates:
              - Path=/products, /products/{id}
            filters:
              - TokenRelay=

    #            filters:
    #              - SetPath=/get


server:
  port: 8080