spring:
  application:
    name: gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: hello-world
            uri: http://localhost:8081
            predicates:
              - Path=/products/{id}
#            filters:
#              - SetPath=/get

server:
  port: 8080